/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness/readiness check, including the database connection */
    get: operations['HealthController_check_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/exchange-rates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rates from KRW to every display currency, for client-side conversion */
    get: operations['ExchangeRatesController_findAll_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/exchange-rates/{currency}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Create or replace the KRW -> currency rate (takes effect immediately) */
    put: operations['AdminExchangeRatesController_upsert_v1'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an account; sets the refresh-token cookie */
    post: operations['AuthController_register_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign in; sets the refresh-token cookie */
    post: operations['AuthController_login_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the refresh-token cookie and get a new access token */
    post: operations['AuthController_refresh_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the current session and clear the cookie */
    post: operations['AuthController_logout_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The authenticated user */
    get: operations['AuthController_me_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cities, ordered for display (sortOrder) */
    get: operations['CitiesController_list_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/cities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cities with every translation */
    get: operations['AdminCitiesController_list_v1'];
    put?: never;
    /** Create a city (the "en" translation is required) */
    post: operations['AdminCitiesController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/cities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminCitiesController_findOne_v1'];
    put?: never;
    post?: never;
    /** Delete a city without districts, places, accommodations or cost estimates */
    delete: operations['AdminCitiesController_remove_v1'];
    options?: never;
    head?: never;
    /** Update fields and/or translations; locales not sent are kept */
    patch: operations['AdminCitiesController_update_v1'];
    trace?: never;
  };
  '/api/v1/admin/districts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Districts with every translation, optionally of one city */
    get: operations['AdminDistrictsController_list_v1'];
    put?: never;
    /** Create a district in a city (the "en" translation is required) */
    post: operations['AdminDistrictsController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/districts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminDistrictsController_findOne_v1'];
    put?: never;
    post?: never;
    delete: operations['AdminDistrictsController_remove_v1'];
    options?: never;
    head?: never;
    /** Update fields and/or translations; locales not sent are kept */
    patch: operations['AdminDistrictsController_update_v1'];
    trace?: never;
  };
  '/api/v1/cities/{citySlug}/places': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Places of a city with filters, search, sorting and pagination */
    get: operations['PlacesController_list_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cities/{citySlug}/map': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lightweight map markers for every place of a city (cached) */
    get: operations['PlacesController_map_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/places': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Places with every translation, optionally filtered */
    get: operations['AdminPlacesController_list_v1'];
    put?: never;
    /** Create a place (the "en" translation is required) */
    post: operations['AdminPlacesController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/places/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminPlacesController_findOne_v1'];
    put?: never;
    post?: never;
    /** Delete a place without reviews (its favorites are removed too) */
    delete: operations['AdminPlacesController_remove_v1'];
    options?: never;
    head?: never;
    /** Update fields and/or translations; locales not sent are kept */
    patch: operations['AdminPlacesController_update_v1'];
    trace?: never;
  };
  '/api/v1/cities/{citySlug}/accommodations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Accommodations of a city, filtered by travel style (tier), cheapest first */
    get: operations['AccommodationsController_list_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accommodations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminAccommodationsController_list_v1'];
    put?: never;
    post: operations['AdminAccommodationsController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accommodations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminAccommodationsController_findOne_v1'];
    put?: never;
    post?: never;
    delete: operations['AdminAccommodationsController_remove_v1'];
    options?: never;
    head?: never;
    patch: operations['AdminAccommodationsController_update_v1'];
    trace?: never;
  };
  '/api/v1/places/{slug}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reviews of a place, newest first (each in its original language) */
    get: operations['ReviewsController_list_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/places/{id}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Review a place (once per user); updates its rating */
    post: operations['ReviewsController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reviews/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a review (author or admin); updates the place rating */
    delete: operations['ReviewsController_remove_v1'];
    options?: never;
    head?: never;
    /** Edit a review (author or admin); updates the place rating */
    patch: operations['ReviewsController_update_v1'];
    trace?: never;
  };
  '/api/v1/users/me/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reviews written by the authenticated user, newest first */
    get: operations['ReviewsController_mine_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/places/{id}/favorite': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Whether the authenticated user favorited this place */
    get: operations['FavoritesController_status_v1'];
    put?: never;
    /** Favorite a place (idempotent) */
    post: operations['FavoritesController_add_v1'];
    /** Remove a place from favorites (idempotent) */
    delete: operations['FavoritesController_remove_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/favorites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Favorite places of the authenticated user, most recent first */
    get: operations['FavoritesController_mine_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cost-estimates/calculate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Estimate the cost of a trip
     * @description rooms = ceil(people / 2); nights = max(days - 1, 1); lodging = rooms × nightly rate × nights; food, transport and activities = people × daily cost × days. Amounts in KRW and in `currency`.
     */
    post: operations['CostEstimatesController_calculate_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/cost-estimates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminCostEstimatesController_list_v1'];
    put?: never;
    post: operations['AdminCostEstimatesController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/cost-estimates/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminCostEstimatesController_findOne_v1'];
    put?: never;
    post?: never;
    delete: operations['AdminCostEstimatesController_remove_v1'];
    options?: never;
    head?: never;
    patch: operations['AdminCostEstimatesController_update_v1'];
    trace?: never;
  };
  '/api/v1/cities/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A city with its districts and the number of places per category */
    get: operations['CityOverviewController_findOne_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/places/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A place with its city, district and newest reviews */
    get: operations['PlaceOverviewController_findOne_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ExchangeRateDto: {
      /**
       * @example USD
       * @enum {string}
       */
      currency: 'USD' | 'BRL';
      /**
       * @description How many units of `currency` one KRW buys.
       * @example 0.00072
       */
      rate: number;
      /**
       * @description Where the rate came from.
       * @example env
       */
      source: string;
      /**
       * Format: date-time
       * @description When the rate was last updated.
       */
      updatedAt: string;
    };
    ExchangeRatesResponseDto: {
      /**
       * @description Every price in the API is stored in this currency.
       * @example KRW
       */
      base: string;
      rates: components['schemas']['ExchangeRateDto'][];
    };
    UpdateExchangeRateDto: {
      /**
       * @description How many units of the currency one KRW buys. Positive, at most 8 decimal places.
       * @example 0.00072
       */
      rate: number;
    };
    RegisterDto: {
      /** @example Ana Souza */
      name: string;
      /**
       * Format: email
       * @example ana.souza@example.com
       */
      email: string;
      /** @example correct horse battery staple */
      password: string;
    };
    UserDto: {
      /** Format: uuid */
      id: string;
      /** @example Ana Souza */
      name: string;
      /** @example ana.souza@example.com */
      email: string;
      /**
       * @example USER
       * @enum {string}
       */
      role: 'USER' | 'ADMIN';
      /** Format: date-time */
      createdAt: string;
    };
    AuthResponseDto: {
      /** @description Short-lived JWT. Send as `Authorization: Bearer <token>`. */
      accessToken: string;
      /**
       * @example Bearer
       * @enum {string}
       */
      tokenType: 'Bearer';
      /**
       * @description Access token lifetime in seconds.
       * @example 900
       */
      expiresIn: number;
      user: components['schemas']['UserDto'];
    };
    LoginDto: {
      /**
       * Format: email
       * @example ana.souza@example.com
       */
      email: string;
      password: string;
    };
    RefreshResponseDto: {
      accessToken: string;
      /**
       * @example Bearer
       * @enum {string}
       */
      tokenType: 'Bearer';
      /** @example 900 */
      expiresIn: number;
    };
    PaginationMetaDto: {
      /** @example 1 */
      page: number;
      /** @example 20 */
      limit: number;
      /** @example 37 */
      total: number;
      /** @example 2 */
      totalPages: number;
    };
    CityDto: {
      /** Format: uuid */
      id: string;
      /** @example seoul */
      slug: string;
      /** @enum {string} */
      locale: 'en' | 'pt-BR';
      /** @example Seoul */
      name: string;
      /** @example 서울 */
      nameKo: string;
      description: string;
      bestTimeToVisit: string;
      heroImageUrl: string;
      latitude: number;
      longitude: number;
      population?: number | null;
      isFeatured: boolean;
    };
    CityTextDto: {
      /** @example Seoul */
      name: string;
      description: string;
      /** @example Spring (April–May) and autumn (September–November). */
      bestTimeToVisit: string;
    };
    AdminCityTranslationsDto: {
      en: components['schemas']['CityTextDto'];
      'pt-BR'?: components['schemas']['CityTextDto'];
    };
    AdminCityDto: {
      /** Format: uuid */
      id: string;
      slug: string;
      nameKo: string;
      heroImageUrl: string;
      latitude: number;
      longitude: number;
      population?: number | null;
      isFeatured: boolean;
      sortOrder: number;
      translations: components['schemas']['AdminCityTranslationsDto'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CityTranslationsDto: {
      /** @description Required: the default locale. */
      en: components['schemas']['CityTextDto'];
      'pt-BR'?: components['schemas']['CityTextDto'];
    };
    CreateCityDto: {
      /** @example seoul */
      slug: string;
      /** @example 서울 */
      nameKo: string;
      /**
       * Format: uri
       * @example https://picsum.photos/seed/seoul/1600/900
       */
      heroImageUrl: string;
      /** @example 37.5665 */
      latitude: number;
      /** @example 126.978 */
      longitude: number;
      /** @example 9400000 */
      population?: number;
      /** @default false */
      isFeatured: boolean;
      /** @default 0 */
      sortOrder: number;
      translations: components['schemas']['CityTranslationsDto'];
    };
    PartialCityTextDto: {
      /** @example Seoul */
      name?: string;
      description?: string;
      /** @example Spring (April–May) and autumn (September–November). */
      bestTimeToVisit?: string;
    };
    UpdateCityTranslationsDto: {
      en?: components['schemas']['PartialCityTextDto'];
      /** @description Send null to remove the Portuguese translation. */
      'pt-BR'?: components['schemas']['PartialCityTextDto'] | null;
    };
    UpdateCityDto: {
      /** @example seoul */
      slug?: string;
      /** @example 서울 */
      nameKo?: string;
      /**
       * Format: uri
       * @example https://picsum.photos/seed/seoul/1600/900
       */
      heroImageUrl?: string;
      /** @example 37.5665 */
      latitude?: number;
      /** @example 126.978 */
      longitude?: number;
      /** @example 9400000 */
      population?: number;
      /** @default false */
      isFeatured: boolean;
      /** @default 0 */
      sortOrder: number;
      /** @description Only the locales sent are changed; the others are kept. */
      translations?: components['schemas']['UpdateCityTranslationsDto'];
    };
    DistrictTextDto: {
      /** @example Hongdae */
      name: string;
      description: string;
    };
    AdminDistrictTranslationsDto: {
      en: components['schemas']['DistrictTextDto'];
      'pt-BR'?: components['schemas']['DistrictTextDto'];
    };
    AdminDistrictDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      cityId: string;
      slug: string;
      nameKo: string;
      latitude: number;
      longitude: number;
      translations: components['schemas']['AdminDistrictTranslationsDto'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    DistrictTranslationsDto: {
      en: components['schemas']['DistrictTextDto'];
      'pt-BR'?: components['schemas']['DistrictTextDto'];
    };
    CreateDistrictDto: {
      /** Format: uuid */
      cityId: string;
      /**
       * @description Unique within its city.
       * @example hongdae
       */
      slug: string;
      /** @example 홍대 */
      nameKo: string;
      /** @example 37.5563 */
      latitude: number;
      /** @example 126.9236 */
      longitude: number;
      translations: components['schemas']['DistrictTranslationsDto'];
    };
    PartialDistrictTextDto: {
      /** @example Hongdae */
      name?: string;
      description?: string;
    };
    UpdateDistrictTranslationsDto: {
      en?: components['schemas']['PartialDistrictTextDto'];
      /** @description null removes it. */
      'pt-BR'?: components['schemas']['PartialDistrictTextDto'] | null;
    };
    UpdateDistrictDto: {
      /**
       * @description Unique within its city.
       * @example hongdae
       */
      slug?: string;
      /** @example 홍대 */
      nameKo?: string;
      /** @example 37.5563 */
      latitude?: number;
      /** @example 126.9236 */
      longitude?: number;
      translations?: components['schemas']['UpdateDistrictTranslationsDto'];
    };
    TrailDto: {
      /** @enum {string} */
      difficulty: 'EASY' | 'MODERATE' | 'HARD';
      /** @example 8.4 */
      distanceKm: number;
      /** @example 270 */
      durationMinutes: number;
      /** @example 700 */
      elevationGainM: number;
    };
    PlaceSummaryDto: {
      /** Format: uuid */
      id: string;
      slug: string;
      /**
       * @description Language of name/description after fallback.
       * @enum {string}
       */
      locale: 'en' | 'pt-BR';
      /** @enum {string} */
      category:
        | 'RESTAURANT'
        | 'NIGHTLIFE'
        | 'HIKING'
        | 'ATTRACTION'
        | 'CAFE'
        | 'SHOPPING'
        | 'CULTURE'
        | 'NATURE';
      name: string;
      nameKo: string;
      description: string;
      /** Format: uuid */
      districtId?: string | null;
      latitude: number;
      longitude: number;
      priceLevel: number;
      /** @description In KRW; convert with GET /exchange-rates. */
      averageSpendKRW: number;
      /** @example 4.67 */
      ratingAvg: number;
      ratingCount: number;
      tags: string[];
      imageUrl?: string | null;
      trail?: components['schemas']['TrailDto'] | null;
    };
    MapPointDto: {
      /** Format: uuid */
      id: string;
      slug: string;
      name: string;
      /** @enum {string} */
      category:
        | 'RESTAURANT'
        | 'NIGHTLIFE'
        | 'HIKING'
        | 'ATTRACTION'
        | 'CAFE'
        | 'SHOPPING'
        | 'CULTURE'
        | 'NATURE';
      latitude: number;
      longitude: number;
    };
    PlaceTextDto: {
      /** @example Gyeongbokgung Palace */
      name: string;
      description: string;
      /** @example Closed on Tuesdays. */
      openingHoursNote?: string | null;
    };
    AdminPlaceTranslationsDto: {
      en: components['schemas']['PlaceTextDto'];
      'pt-BR'?: components['schemas']['PlaceTextDto'];
    };
    AdminPlaceDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      cityId: string;
      /** Format: uuid */
      districtId?: string | null;
      /** @enum {string} */
      category:
        | 'RESTAURANT'
        | 'NIGHTLIFE'
        | 'HIKING'
        | 'ATTRACTION'
        | 'CAFE'
        | 'SHOPPING'
        | 'CULTURE'
        | 'NATURE';
      slug: string;
      nameKo: string;
      address: string;
      latitude: number;
      longitude: number;
      priceLevel: number;
      averageSpendKRW: number;
      openingHours?: Record<string, never> | null;
      website?: string | null;
      imageUrls: string[];
      tags: string[];
      trail?: components['schemas']['TrailDto'] | null;
      ratingAvg: number;
      ratingCount: number;
      translations: components['schemas']['AdminPlaceTranslationsDto'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PlaceTranslationsDto: {
      en: components['schemas']['PlaceTextDto'];
      'pt-BR'?: components['schemas']['PlaceTextDto'];
    };
    CreatePlaceDto: {
      /** Format: uuid */
      cityId: string;
      /**
       * Format: uuid
       * @description Must belong to the same city.
       */
      districtId?: string | null;
      /** @enum {string} */
      category:
        | 'RESTAURANT'
        | 'NIGHTLIFE'
        | 'HIKING'
        | 'ATTRACTION'
        | 'CAFE'
        | 'SHOPPING'
        | 'CULTURE'
        | 'NATURE';
      /**
       * @description Globally unique.
       * @example gyeongbokgung-palace
       */
      slug: string;
      /** @example 경복궁 */
      nameKo: string;
      /** @example 161 Sajik-ro, Jongno-gu, Seoul */
      address: string;
      latitude: number;
      longitude: number;
      priceLevel: number;
      /** @example 3000 */
      averageSpendKRW: number;
      /** @description Weekly schedule (see OpeningHours). */
      openingHours?: Record<string, never> | null;
      /** Format: uri */
      website?: string | null;
      /** @default [] */
      imageUrls: string[];
      /**
       * @default []
       * @example [
       *       "palace",
       *       "history"
       *     ]
       */
      tags: string[];
      /** @description Only for HIKING places. */
      trail?: components['schemas']['TrailDto'] | null;
      translations: components['schemas']['PlaceTranslationsDto'];
    };
    PartialPlaceTextDto: {
      /** @example Gyeongbokgung Palace */
      name?: string;
      description?: string;
      /** @example Closed on Tuesdays. */
      openingHoursNote?: string | null;
    };
    UpdatePlaceTranslationsDto: {
      en?: components['schemas']['PartialPlaceTextDto'];
      /** @description null removes it. */
      'pt-BR'?: components['schemas']['PartialPlaceTextDto'] | null;
    };
    UpdatePlaceDto: {
      /**
       * Format: uuid
       * @description Must belong to the same city.
       */
      districtId?: string | null;
      /** @enum {string} */
      category?:
        | 'RESTAURANT'
        | 'NIGHTLIFE'
        | 'HIKING'
        | 'ATTRACTION'
        | 'CAFE'
        | 'SHOPPING'
        | 'CULTURE'
        | 'NATURE';
      /**
       * @description Globally unique.
       * @example gyeongbokgung-palace
       */
      slug?: string;
      /** @example 경복궁 */
      nameKo?: string;
      /** @example 161 Sajik-ro, Jongno-gu, Seoul */
      address?: string;
      latitude?: number;
      longitude?: number;
      priceLevel?: number;
      /** @example 3000 */
      averageSpendKRW?: number;
      /** @description Weekly schedule (see OpeningHours). */
      openingHours?: Record<string, never> | null;
      /** Format: uri */
      website?: string | null;
      /** @default [] */
      imageUrls: string[];
      /**
       * @default []
       * @example [
       *       "palace",
       *       "history"
       *     ]
       */
      tags: string[];
      /** @description Only for HIKING places. */
      trail?: components['schemas']['TrailDto'] | null;
      translations?: components['schemas']['UpdatePlaceTranslationsDto'];
    };
    AccommodationDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      cityId: string;
      /** Format: uuid */
      districtId?: string | null;
      slug: string;
      name: string;
      /** @enum {string} */
      type: 'HOTEL' | 'HOSTEL' | 'GUESTHOUSE' | 'HANOK' | 'APARTMENT';
      /** @enum {string} */
      tier: 'BUDGET' | 'MID' | 'LUXURY';
      /** @description In KRW; convert with GET /exchange-rates. */
      pricePerNightKRW: number;
      latitude: number;
      longitude: number;
      bookingUrl?: string | null;
      imageUrls: string[];
    };
    AdminAccommodationDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      cityId: string;
      /** Format: uuid */
      districtId?: string | null;
      slug: string;
      name: string;
      /** @enum {string} */
      type: 'HOTEL' | 'HOSTEL' | 'GUESTHOUSE' | 'HANOK' | 'APARTMENT';
      /** @enum {string} */
      tier: 'BUDGET' | 'MID' | 'LUXURY';
      /** @description In KRW; convert with GET /exchange-rates. */
      pricePerNightKRW: number;
      latitude: number;
      longitude: number;
      bookingUrl?: string | null;
      imageUrls: string[];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateAccommodationDto: {
      /** Format: uuid */
      cityId: string;
      /**
       * Format: uuid
       * @description Must belong to the same city.
       */
      districtId?: string | null;
      /**
       * @description Globally unique.
       * @example the-shilla-seoul
       */
      slug: string;
      /**
       * @description Proper name; not translated.
       * @example The Shilla Seoul
       */
      name: string;
      /** @enum {string} */
      type: 'HOTEL' | 'HOSTEL' | 'GUESTHOUSE' | 'HANOK' | 'APARTMENT';
      /** @enum {string} */
      tier: 'BUDGET' | 'MID' | 'LUXURY';
      /** @example 650000 */
      pricePerNightKRW: number;
      latitude: number;
      longitude: number;
      /** Format: uri */
      bookingUrl?: string | null;
      /** @default [] */
      imageUrls: string[];
    };
    UpdateAccommodationDto: {
      /**
       * Format: uuid
       * @description Must belong to the same city.
       */
      districtId?: string | null;
      /**
       * @description Globally unique.
       * @example the-shilla-seoul
       */
      slug?: string;
      /**
       * @description Proper name; not translated.
       * @example The Shilla Seoul
       */
      name?: string;
      /** @enum {string} */
      type?: 'HOTEL' | 'HOSTEL' | 'GUESTHOUSE' | 'HANOK' | 'APARTMENT';
      /** @enum {string} */
      tier?: 'BUDGET' | 'MID' | 'LUXURY';
      /** @example 650000 */
      pricePerNightKRW?: number;
      latitude?: number;
      longitude?: number;
      /** Format: uri */
      bookingUrl?: string | null;
      /** @default [] */
      imageUrls: string[];
    };
    ReviewAuthorDto: {
      /** Format: uuid */
      id: string;
      /** @example Ana Souza */
      name: string;
    };
    ReviewDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      placeId: string;
      rating: number;
      title: string;
      comment: string;
      /**
       * @description Language it was written in (never translated).
       * @enum {string}
       */
      locale: 'en' | 'pt-BR';
      /** @example 2026-04-12 */
      visitedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      author: components['schemas']['ReviewAuthorDto'];
    };
    CreateReviewDto: {
      /** @example 5 */
      rating: number;
      /** @example Go early and rent a hanbok */
      title: string;
      comment: string;
      /**
       * @description Day of the visit (YYYY-MM-DD), not in the future.
       * @example 2026-04-12
       */
      visitedAt?: string;
      /**
       * @description Language the review is written in. Defaults to the request locale.
       * @enum {string}
       */
      locale?: 'en' | 'pt-BR';
    };
    UpdateReviewDto: {
      /** @example 5 */
      rating?: number;
      /** @example Go early and rent a hanbok */
      title?: string;
      comment?: string;
      /**
       * @description Day of the visit (YYYY-MM-DD), not in the future.
       * @example 2026-04-12
       */
      visitedAt?: string;
      /**
       * @description Language the review is written in. Defaults to the request locale.
       * @enum {string}
       */
      locale?: 'en' | 'pt-BR';
    };
    ReviewedPlaceDto: {
      /** Format: uuid */
      id: string;
      slug: string;
      name: string;
    };
    MyReviewDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      placeId: string;
      rating: number;
      title: string;
      comment: string;
      /**
       * @description Language it was written in (never translated).
       * @enum {string}
       */
      locale: 'en' | 'pt-BR';
      /** @example 2026-04-12 */
      visitedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      author: components['schemas']['ReviewAuthorDto'];
      place: components['schemas']['ReviewedPlaceDto'];
    };
    FavoriteStatusDto: {
      favorited: boolean;
    };
    CalculateCostDto: {
      /** @example seoul */
      citySlug: string;
      /** @example 2 */
      people: number;
      /** @example 7 */
      days: number;
      /**
       * @description Travel style.
       * @example MID
       * @enum {string}
       */
      tier: 'BUDGET' | 'MID' | 'LUXURY';
      /**
       * @description Currency for the converted amounts. Defaults to USD for en and BRL for pt-BR.
       * @enum {string}
       */
      currency?: 'USD' | 'BRL';
    };
    CalculatedCityDto: {
      slug: string;
      name: string;
      /** @enum {string} */
      locale: 'en' | 'pt-BR';
    };
    UsedExchangeRateDto: {
      /** @example KRW */
      base: string;
      /** @enum {string} */
      currency: 'USD' | 'BRL';
      /** @example 0.00072 */
      rate: number;
      /** Format: date-time */
      updatedAt: string;
    };
    MoneyDto: {
      /**
       * @description Amount in KRW (rounded to the won).
       * @example 1250000
       */
      krw: number;
      /**
       * @description Amount in the requested currency (rounded to cents).
       * @example 900
       */
      amount: number;
    };
    BreakdownDto: {
      lodging: components['schemas']['MoneyDto'];
      food: components['schemas']['MoneyDto'];
      transport: components['schemas']['MoneyDto'];
      activities: components['schemas']['MoneyDto'];
    };
    CostCalculationDto: {
      city: components['schemas']['CalculatedCityDto'];
      people: number;
      days: number;
      /** @description days - 1, at least 1. */
      nights: number;
      /** @description ceil(people / 2). */
      rooms: number;
      /** @enum {string} */
      tier: 'BUDGET' | 'MID' | 'LUXURY';
      /** @enum {string} */
      currency: 'USD' | 'BRL';
      exchangeRate: components['schemas']['UsedExchangeRateDto'];
      breakdown: components['schemas']['BreakdownDto'];
      total: components['schemas']['MoneyDto'];
      /** @description Average spend per day of the trip. */
      perDay: components['schemas']['MoneyDto'];
      /** @description Average spend per traveler. */
      perPerson: components['schemas']['MoneyDto'];
    };
    CostEstimateDto: {
      /** Format: uuid */
      cityId: string;
      /** @enum {string} */
      tier: 'BUDGET' | 'MID' | 'LUXURY';
      /** @example 180000 */
      lodgingPerRoomPerNightKRW: number;
      /** @example 70000 */
      foodPerPersonPerDayKRW: number;
      /** @example 15000 */
      transportPerPersonPerDayKRW: number;
      /** @example 40000 */
      activitiesPerPersonPerDayKRW: number;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateCostEstimateDto: {
      /** Format: uuid */
      cityId: string;
      /** @enum {string} */
      tier: 'BUDGET' | 'MID' | 'LUXURY';
      /** @example 180000 */
      lodgingPerRoomPerNightKRW: number;
      /** @example 70000 */
      foodPerPersonPerDayKRW: number;
      /** @example 15000 */
      transportPerPersonPerDayKRW: number;
      /** @example 40000 */
      activitiesPerPersonPerDayKRW: number;
    };
    UpdateCostEstimateDto: {
      /** @example 180000 */
      lodgingPerRoomPerNightKRW?: number;
      /** @example 70000 */
      foodPerPersonPerDayKRW?: number;
      /** @example 15000 */
      transportPerPersonPerDayKRW?: number;
      /** @example 40000 */
      activitiesPerPersonPerDayKRW?: number;
    };
    DistrictDto: {
      /** Format: uuid */
      id: string;
      slug: string;
      /** @enum {string} */
      locale: 'en' | 'pt-BR';
      name: string;
      nameKo: string;
      description: string;
      latitude: number;
      longitude: number;
    };
    CityOverviewDto: {
      /** Format: uuid */
      id: string;
      /** @example seoul */
      slug: string;
      /** @enum {string} */
      locale: 'en' | 'pt-BR';
      /** @example Seoul */
      name: string;
      /** @example 서울 */
      nameKo: string;
      description: string;
      bestTimeToVisit: string;
      heroImageUrl: string;
      latitude: number;
      longitude: number;
      population?: number | null;
      isFeatured: boolean;
      districts: components['schemas']['DistrictDto'][];
      /**
       * @description Number of places per category (every category present, 0 when empty).
       * @example {
       *       "RESTAURANT": 5,
       *       "NIGHTLIFE": 5,
       *       "HIKING": 5,
       *       "ATTRACTION": 5,
       *       "CAFE": 5,
       *       "SHOPPING": 5,
       *       "CULTURE": 5,
       *       "NATURE": 5
       *     }
       */
      placeCounts: Record<string, never>;
    };
    PlaceAreaDto: {
      /** Format: uuid */
      id: string;
      slug: string;
      name: string;
    };
    PlaceOverviewDto: {
      /** Format: uuid */
      id: string;
      slug: string;
      /**
       * @description Language of name/description after fallback.
       * @enum {string}
       */
      locale: 'en' | 'pt-BR';
      /** @enum {string} */
      category:
        | 'RESTAURANT'
        | 'NIGHTLIFE'
        | 'HIKING'
        | 'ATTRACTION'
        | 'CAFE'
        | 'SHOPPING'
        | 'CULTURE'
        | 'NATURE';
      name: string;
      nameKo: string;
      description: string;
      /** Format: uuid */
      districtId?: string | null;
      latitude: number;
      longitude: number;
      priceLevel: number;
      /** @description In KRW; convert with GET /exchange-rates. */
      averageSpendKRW: number;
      /** @example 4.67 */
      ratingAvg: number;
      ratingCount: number;
      tags: string[];
      imageUrl?: string | null;
      trail?: components['schemas']['TrailDto'] | null;
      /** Format: uuid */
      cityId: string;
      address: string;
      /** @description Weekly schedule (Asia/Seoul). */
      openingHours?: Record<string, never> | null;
      openingHoursNote?: string | null;
      website?: string | null;
      imageUrls: string[];
      city: components['schemas']['PlaceAreaDto'];
      district?: components['schemas']['PlaceAreaDto'] | null;
      /** @description The 5 newest reviews (see /places/:slug/reviews). */
      recentReviews: components['schemas']['ReviewDto'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example ok
             * @enum {string}
             */
            status?: 'ok' | 'degraded';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example error
             * @enum {string}
             */
            status?: 'error' | 'shutting_down';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
  ExchangeRatesController_findAll_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExchangeRatesResponseDto'];
        };
      };
    };
  };
  AdminExchangeRatesController_upsert_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target currency (case-insensitive). */
        currency: 'USD' | 'BRL';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateExchangeRateDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExchangeRateDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description EMAIL_ALREADY_REGISTERED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description INVALID_CREDENTIALS (same for unknown email and wrong password) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RefreshResponseDto'];
        };
      };
      /** @description INVALID_REFRESH_TOKEN or REFRESH_TOKEN_REUSED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description UNAUTHORIZED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CitiesController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        /** @description Only cities featured on the home page. */
        featured?: boolean;
        /** @description Content language. Unsupported values fall back to "en". Takes precedence over Accept-Language. */
        locale?: 'en' | 'pt-BR';
      };
      header?: {
        /** @description Used when ?locale is absent. */
        'Accept-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['CityDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
    };
  };
  AdminCitiesController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['AdminCityDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCitiesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCityDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCityDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CONFLICT: slug already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCitiesController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCityDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCitiesController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CONFLICT: the city still has related records */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCitiesController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCityDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCityDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminDistrictsController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        cityId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['AdminDistrictDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminDistrictsController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDistrictDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminDistrictDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CONFLICT: slug already used in this city */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminDistrictsController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminDistrictDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminDistrictsController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CONFLICT: places or accommodations still reference it */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminDistrictsController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateDistrictDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminDistrictDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlacesController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        category?:
          | 'RESTAURANT'
          | 'NIGHTLIFE'
          | 'HIKING'
          | 'ATTRACTION'
          | 'CAFE'
          | 'SHOPPING'
          | 'CULTURE'
          | 'NATURE';
        districtId?: string;
        /** @description One or more levels, comma-separated: "1,2". */
        priceLevel?: string[];
        /** @description Places having every tag, comma-separated. */
        tags?: string[];
        /** @description Hiking places only. */
        difficulty?: 'EASY' | 'MODERATE' | 'HARD';
        /** @description Minimum average rating. */
        minRating?: number;
        sort?: 'rating' | 'price';
        /** @description Matches name/description (in the requested language and English), Korean name or a tag. */
        search?: string;
        /** @description Content language. Unsupported values fall back to "en". Takes precedence over Accept-Language. */
        locale?: 'en' | 'pt-BR';
      };
      header?: {
        /** @description Used when ?locale is absent. */
        'Accept-Language'?: string;
      };
      path: {
        citySlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['PlaceSummaryDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
      /** @description CITY_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlacesController_map_v1: {
    parameters: {
      query?: {
        category?:
          | 'RESTAURANT'
          | 'NIGHTLIFE'
          | 'HIKING'
          | 'ATTRACTION'
          | 'CAFE'
          | 'SHOPPING'
          | 'CULTURE'
          | 'NATURE';
        /** @description Content language. Unsupported values fall back to "en". Takes precedence over Accept-Language. */
        locale?: 'en' | 'pt-BR';
      };
      header?: {
        /** @description Used when ?locale is absent. */
        'Accept-Language'?: string;
      };
      path: {
        citySlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MapPointDto'][];
        };
      };
      /** @description CITY_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminPlacesController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        cityId?: string;
        category?:
          | 'RESTAURANT'
          | 'NIGHTLIFE'
          | 'HIKING'
          | 'ATTRACTION'
          | 'CAFE'
          | 'SHOPPING'
          | 'CULTURE'
          | 'NATURE';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['AdminPlaceDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminPlacesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePlaceDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminPlaceDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CONFLICT: slug already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminPlacesController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminPlaceDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminPlacesController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CONFLICT: the place has reviews */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminPlacesController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePlaceDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminPlaceDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AccommodationsController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        tier?: 'BUDGET' | 'MID' | 'LUXURY';
        type?: 'HOTEL' | 'HOSTEL' | 'GUESTHOUSE' | 'HANOK' | 'APARTMENT';
        districtId?: string;
        /** @description "-price" = most expensive first. */
        sort?: 'price' | '-price';
      };
      header?: never;
      path: {
        citySlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['AccommodationDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
      /** @description CITY_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminAccommodationsController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        cityId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['AdminAccommodationDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminAccommodationsController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAccommodationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccommodationDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CONFLICT: slug already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminAccommodationsController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccommodationDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminAccommodationsController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminAccommodationsController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAccommodationDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccommodationDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReviewsController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['ReviewDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
      /** @description PLACE_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReviewsController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateReviewDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReviewDto'];
        };
      };
      /** @description PLACE_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description REVIEW_ALREADY_EXISTS */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReviewsController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description FORBIDDEN: not the author */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReviewsController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateReviewDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReviewDto'];
        };
      };
      /** @description FORBIDDEN: not the author */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReviewsController_mine_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        /** @description Content language. Unsupported values fall back to "en". Takes precedence over Accept-Language. */
        locale?: 'en' | 'pt-BR';
      };
      header?: {
        /** @description Used when ?locale is absent. */
        'Accept-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['MyReviewDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
    };
  };
  FavoritesController_status_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FavoriteStatusDto'];
        };
      };
      /** @description PLACE_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FavoritesController_add_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description PLACE_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FavoritesController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description PLACE_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FavoritesController_mine_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        /** @description Content language. Unsupported values fall back to "en". Takes precedence over Accept-Language. */
        locale?: 'en' | 'pt-BR';
      };
      header?: {
        /** @description Used when ?locale is absent. */
        'Accept-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['PlaceSummaryDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
    };
  };
  CostEstimatesController_calculate_v1: {
    parameters: {
      query?: {
        /** @description Content language. Unsupported values fall back to "en". Takes precedence over Accept-Language. */
        locale?: 'en' | 'pt-BR';
      };
      header?: {
        /** @description Used when ?locale is absent. */
        'Accept-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CalculateCostDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CostCalculationDto'];
        };
      };
      /** @description CITY_NOT_FOUND or COST_ESTIMATE_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCostEstimatesController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        cityId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['CostEstimateDto'][];
            meta: components['schemas']['PaginationMetaDto'];
          };
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCostEstimatesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCostEstimateDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CostEstimateDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CONFLICT: this city already has an estimate for the tier */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCostEstimatesController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CostEstimateDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCostEstimatesController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminCostEstimatesController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCostEstimateDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CostEstimateDto'];
        };
      };
      /** @description FORBIDDEN: requires the ADMIN role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CityOverviewController_findOne_v1: {
    parameters: {
      query?: {
        /** @description Content language. Unsupported values fall back to "en". Takes precedence over Accept-Language. */
        locale?: 'en' | 'pt-BR';
      };
      header?: {
        /** @description Used when ?locale is absent. */
        'Accept-Language'?: string;
      };
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CityOverviewDto'];
        };
      };
      /** @description CITY_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlaceOverviewController_findOne_v1: {
    parameters: {
      query?: {
        /** @description Content language. Unsupported values fall back to "en". Takes precedence over Accept-Language. */
        locale?: 'en' | 'pt-BR';
      };
      header?: {
        /** @description Used when ?locale is absent. */
        'Accept-Language'?: string;
      };
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlaceOverviewDto'];
        };
      };
      /** @description PLACE_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
